### ISSUE TITLE
Develop Metanorma Windows setup instructions

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-windows-setup#1]
Like the macOS version.

https://github.com/riboseinc/metanorma-macos-setup/

* Package manager: use chocolatey
  * supports PlantUML, Ruby 2.5, Java, nodejs
  * puppeteer can be installed via npm (https://github.com/GoogleChrome/puppeteer)
  * sublime (https://chocolatey.org/packages?q=sublime)

Installing Chocolatey:
* https://medium.com/@JockDaRock/installing-the-chocolatey-package-manager-for-windows-3b1bdd0dbb49

**Comment by opoudjis** [comment]
As discussed, I have patchy access to a Windows box, and no great desire to gain that level of expertise. I can probably get this done, but it won't be immediate.

**Comment by ronaldtse** [comment]
libsass: http://libsass.ocbnet.ch/installer/

Nokogiri is available via the Ruby installer.

**Comment by CAMOBAP** [comment]
This was implemented in scope of RPs https://github.com/riboseinc/metanorma-windows-setup/pull/2, https://github.com/riboseinc/metanorma-windows-setup/pull/3, https://github.com/riboseinc/metanorma-windows-setup/pull/5
