### ISSUE TITLE
Make AppVeyor check UNECE Recommendation 42 document build

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-windows-setup#4]
For @CAMOBAP795 .

From #3 

This ticket is to add to the AppVeyor build script to build the UNECE Recommendation 42 document (https://github.com/riboseinc/unece-cefact-recommendation-42/pull/1/files#diff-180360612c6b8c4ed830919bbb4dd459) into this repo, so that we can test directly whether the windows setup script allows building the document immediately.

Thanks!

**Comment by CAMOBAP** [comment]
Done https://github.com/riboseinc/metanorma-windows-setup/pull/5
