### ISSUE TITLE
Split Docker and Native Ruby installation scripts

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-windows-setup#7]

**Comment by ronaldtse** [comment]
For @CAMOBAP795

**Comment by CAMOBAP** [comment]
Done

**Comment by ronaldtse** [comment]
@CAMOBAP795 did we already complete this and have tests and documentation for both methods?

**Comment by CAMOBAP** [comment]
@ronaldtse everything except tests for docker, we already have separate scripts & documentation is up-to-date.

I had difficulties with installing & running docker on appveyor, but recently I have found https://ci.appveyor.com/project/appveyor-tests/docker-ce so maybe make sense to keep this open, I will try to add tests for docker too

**Comment by CAMOBAP** [comment]
@ronaldtse  I propose to close this one because everything is done in scope of it

**Comment by ronaldtse** [comment]
Agree. I think it's hard to install Docker via Chocolatey.

**Comment by CAMOBAP** [comment]
> Agree. I think it's hard to install Docker via Chocolatey.

@ronaldtse  Too many options there and better leave it for user
