### ISSUE TITLE
Create Chocolatey package for Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-windows-setup#9]

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you help update this setup script to use Chocolatey-metanorma? I believe the puppeteer package (and packages from install.config) can be installed using chocolatey dependencies as well?

install.config
```xml
    <package id="git" />
    <package id="sed" />
    <package id="make" />
    <package id="ruby" version="2.3.3"/>
    <package id="xsltproc" />
    <package id="gnuwin32-coreutils.portable" />
    <package id="nodejs" verson="11.3.0" />
    <package id="plantuml" />
```

**Comment by ronaldtse** [comment]
And remove the "gem install" lines since chocolatey-metanorma already does that.

**Comment by CAMOBAP** [comment]
Sure, make sense

**Comment by CAMOBAP** [comment]
@ronaldtse CI in progress
 - https://github.com/riboseinc/chocolatey-metanorma/pull/9
 - https://github.com/riboseinc/metanorma-windows-setup/pull/14

**Comment by CAMOBAP** [comment]
Done
